### ISSUE TITLE
Change port of panel

### ISSUE THREAD

**Issue by finnie2006** [EdyTheCow/docker-pterodactyl#15]
How can i change the port of the panel

**Comment by finnie2006** [comment]
Because port 80 and 443 are already in use on the vps

**Comment by EdyTheCow** [comment]
In that case this specific setup isn't really useful to you unless you move your applications running on those ports under Traefik. For Traefik reverse proxy to work, it needs 80 and 443 ports to be unused.

**Comment by yyewolf** [comment]
For a rootless setup going above 1024 would be required, so is it possible to change the port or no ?
