### ISSUE TITLE
Pool overlaps with other one on this address space

### ISSUE THREAD

**Issue by Fumaz** [EdyTheCow/docker-pterodactyl#27]
Hi, I'm trying to get wings to run on a server, I followed the instructions but when I start my wings container I get the following error:

```
FATAL: [Oct 26 22:31:30.428] failed to configure docker environment error=Error response from daemon: Pool overlaps with other one on this address space
```

**Comment by lukasschachner** [comment]
the pterodactyl network you created probably has an overlapping address space with the docker network the node is trying to create.

you can either painfully change the node config to ot use that or revreate the pterodactyl network with the `--subnet=192.168.0.0/16` flag to resolve this issue

**Comment by nexuma** [comment]
Hello, sorry for commenting on a closed issue but I get the same error and don't know where else I could ask.

When installing the wings agent on the node I get the same message, however I checked every docker network and nothing is overlapping.  So the wings agent is connected to the wings0 (172.24.0.0/16 ) network and the traefik (172.21.0.0/16) network.
I have other containers running that use the traefik network (is that the problem ?) but nothing on the wings0. I have tried a lot of other subnets including 192.168.0.0/16 or even 192.168.123.0/24.

I spent hours trying to fix this, but I'm at a lost. I would be happy to provide anything else needed.

```
INFO: [Apr 12 11:13:15.477] creating missing pterodactyl0 interface, this could take a few seconds...
FATAL: [Apr 12 11:13:15.481] failed to configure docker environment error=Error response from daemon: Pool overlaps with other one on this address space
Stacktrace:
Error response from daemon: Pool overlaps with other one on this address space
```

Sorry if I posted this in the wrong place. -_-'

**Comment by nexuma** [comment]
Okay I fixed it, for those who might stumble upon the same problem here was my fix, which is very weird.

1. I deleted my existing wings agent container and deleted my wings0 network. 
2. Created a new network named pterodactyl_nw (because thats the default network mode), I did this via command line ```docker network create pterodactyl_nw```, you could probably do that in the docker compose file too. 
3. In the docker compose file, I switched my wings0 for pterodactyl_nw and marked it as external. You could also just rename the wings0 in the commented lines to pterodactyl_nw and save yourself step number 2.
```
networks:
 # added these two
  pterodactyl_nw:
    external: true
  # Removed those commented lines
  #  wings0:
  #  name: wings0
  #  driver: bridge
  #  ipam:
  #    config:
  #      - subnet: "172.27.0.0/16"
  #  driver_opts:
  #    com.docker.network.bridge.name: wings0
  traefik_proxy:
    external: true
```
4. I added three lines in the config.yml file before composing up. 
``` 
docker:
  network:
    name: pterodactyl_nw
```
5. Started the container with `docker compose up -d`
6. After that, the error was gone but I could not get a server started, I went back to the configuration file and a bunch of new lines should had appeared. There I had to change the subnet and gateway that the pterodactyl_nw network was using. I changed `interface` `subnet` and `gateway` under `interfaces: v4` to the correct subnet. In my case i changed all `172.18.0.x` to `172.25.0.x` leaving the subnet mask untouched. 

   To find out what the subnet is, I used portainer but you can just use the command `docker network inspect pterodactyl_nw` and just look at the subnet and gateway and use those.

7. I then removed the wings container and recreated it again with the same command. (without deleting the config) and then It worked. Nice !


I have no Idea if this is a stable or secure solution, but currently it works fine.

**Comment by LukasKlein00** [comment]
> Okay I fixed it, for those who might stumble upon the same problem here was my fix, which is very weird.
> 
>     1. I deleted my existing wings agent container and deleted my wings0 network.
> 
>     2. Created a new network named pterodactyl_nw (because thats the default network mode for the wings agent), I did this via command line `docker network create pterodactyl_nw`, you could probably do that in the docker compose file too.
> 
>     3. In the docker compose file, I switched my wings0 for pterodactyl_nw and marked it as external.
> 
> 
> ```
> networks:
>  # added these two
>   pterodactyl_nw:
>     external: true
>   # Removed those commented lines
>   #  wings0:
>   #  name: wings0
>   #  driver: bridge
>   #  ipam:
>   #    config:
>   #      - subnet: "172.27.0.0/16"
>   #  driver_opts:
>   #    com.docker.network.bridge.name: wings0
>   traefik_proxy:
>     external: true
> ```
> 
>     4. I added three lines in the config.yml file before composing up. Not sure why this works.
> 
> 
> ```
> docker:
>   network:
>     name: pterodactyl_nw
> ```
> 
>     5. Started the container with `docker compose up -d`
> 
>     6. After that, the error was gone but I could not get a server started, I went back to the configuration file and a bunch of new lines had appeared. There I had to change the subnet and gateway to those that the pterodactyl_nw network was using. I changed `interface` `subnet` and `gateway` under `interfaces: v4` to the correct subnet. In my case i changed all `172.18.0.x` to `172.25.0.x` leaving the subnet mask untouched.
>        To find out what the subnet is, I used portainer but you can just use the command `docker network inspect pterodactyl_nw` and just look at the subnet and gateway and use those.
> 
>     7. I then removed the wings container and recreated it again with the same command. (without deleting the config) and then It worked. Nice !
> 
> 
> I have no Idea if this is a stable or secure solution, but currently it works fine. You could probably also just add the lines of step number 4 and change the name to your network name and once the container is up change the interface name (which will be pterodactyl_nw) to the name of your network. Then, recreate the container but I didn't try that.

I rarely comment on GitHub but I really really need to thank you. I had a lot of headaches with this and this fixed it for me!

**Comment by Neycy** [comment]
> Okay I fixed it, for those who might stumble upon the same problem here was my fix, which is very weird.
> 
>     1. I deleted my existing wings agent container and deleted my wings0 network.
> 
>     2. Created a new network named pterodactyl_nw (because thats the default network mode for the wings agent), I did this via command line `docker network create pterodactyl_nw`, you could probably do that in the docker compose file too.
> 
>     3. In the docker compose file, I switched my wings0 for pterodactyl_nw and marked it as external.
> 
> 
> ```
> networks:
>  # added these two
>   pterodactyl_nw:
>     external: true
>   # Removed those commented lines
>   #  wings0:
>   #  name: wings0
>   #  driver: bridge
>   #  ipam:
>   #    config:
>   #      - subnet: "172.27.0.0/16"
>   #  driver_opts:
>   #    com.docker.network.bridge.name: wings0
>   traefik_proxy:
>     external: true
> ```
> 
>     4. I added three lines in the config.yml file before composing up. Not sure why this works.
> 
> 
> ```
> docker:
>   network:
>     name: pterodactyl_nw
> ```
> 
>     5. Started the container with `docker compose up -d`
> 
>     6. After that, the error was gone but I could not get a server started, I went back to the configuration file and a bunch of new lines had appeared. There I had to change the subnet and gateway to those that the pterodactyl_nw network was using. I changed `interface` `subnet` and `gateway` under `interfaces: v4` to the correct subnet. In my case i changed all `172.18.0.x` to `172.25.0.x` leaving the subnet mask untouched.
>        To find out what the subnet is, I used portainer but you can just use the command `docker network inspect pterodactyl_nw` and just look at the subnet and gateway and use those.
> 
>     7. I then removed the wings container and recreated it again with the same command. (without deleting the config) and then It worked. Nice !
> 
> 
> I have no Idea if this is a stable or secure solution, but currently it works fine. You could probably also just add the lines of step number 4 and change the name to your network name and once the container is up change the interface name (which will be pterodactyl_nw) to the name of your network. Then, recreate the container but I didn't try that.

Absolutely brilliant, thank you!
